import { test, expect, wavFile, importWav, exportedRecord } from './fixtures';

test('valid compressed multichannel audio is rejected before full PCM decoding', async ({
  page,
}) => {
  await page.addInitScript(() => {
    const original = AudioContext.prototype.decodeAudioData;
    AudioContext.prototype.decodeAudioData = function (...args: Parameters<typeof original>) {
      (window as unknown as { pcmAllocations: number }).pcmAllocations++;
      return original.apply(this, args);
    };
    (window as unknown as { pcmAllocations: number }).pcmAllocations = 0;
  });
  await page.goto('/');
  // Genuine one-second six-channel FLAC silence generated by libsndfile, not a fake header.
  const buffer = Buffer.from(
    'ZkxhQwAAACIQABAAAAAaAAAcBWIq8AAAViLp4vwq0RAWUDR6Y/W7OwwNhAAAKCAAAAByZWZlcmVuY2UgbGliRkxBQyAxLjQuMyAyMDIzMDYyMwAAAAD/+MZYAN4AAAAAAAAAAAAAAAAAAAAAAAC3qv/4xlgB2QAAAAAAAAAAAAAAAAAAAAAAAKK6//jGWALQAAAAAAAAAAAAAAAAAAAAAAAAnYr/+MZYA9cAAAAAAAAAAAAAAAAAAAAAAACImv/4xlgEwgAAAAAAAAAAAAAAAAAAAAAAAOPq//h2WAUGIfQAAAAAAAAAAAAAAAAAAAAAAACuqw==',
    'base64',
  );
  await page
    .getByLabel('Import audio file')
    .setInputFiles({ name: 'surround.flac', mimeType: 'audio/flac', buffer });
  await expect(page.getByRole('alert')).toContainText('mono or stereo');
  expect(
    await page.evaluate(() => (window as unknown as { pcmAllocations: number }).pcmAllocations),
  ).toBe(0);
});

test('ordinary WAV import runs analysis, playback, export, and persisted reopening', async ({
  page,
}) => {
  await page.goto('/');
  const file = await importWav(page);
  const record = await exportedRecord(page);
  expect(record.track.name).toBe(file.name);
  expect(record.analysis.modelVersion).toBe('dsp-template-v1');
  expect(record.analysis.fingerprint).toMatch(/^[a-f0-9]{64}$/);
  expect(record.analysis.duration).toBeCloseTo(6, 2);
  expect(record.analysis.segments.length).toBeGreaterThan(1);
  expect(record.analysis.waveform.length).toBeGreaterThan(0);
  expect(record.analysis.calibration).toBe('uncalibrated');
  await page.getByRole('button', { name: 'Play', exact: true }).click();
  await expect
    .poll(async () => Number(await page.getByLabel('Playback position').inputValue()))
    .toBeGreaterThan(0.2);
  await page.getByRole('button', { name: 'Pause', exact: true }).click();
  await page.getByLabel('Playback position').fill('3');
  await expect
    .poll(async () => Number(await page.getByLabel('Playback position').inputValue()))
    .toBeCloseTo(3, 1);
  await page.reload();
  await page.getByRole('button', { name: `Open analysis: ${file.name}`, exact: true }).click();
  await expect(page.getByTestId('track-title')).toHaveText(file.name);
  await expect(page.getByRole('button', { name: 'Play', exact: true })).toBeDisabled();
  expect((await exportedRecord(page)).analysis).toEqual(record.analysis);
});

test('invalid and corrupt files give actionable errors and permit the next import', async ({
  page,
}) => {
  await page.goto('/');
  await page
    .getByLabel('Import audio file')
    .setInputFiles({ name: 'notes.txt', mimeType: 'text/plain', buffer: Buffer.from('not audio') });
  await expect(page.getByRole('alert')).toContainText('Unsupported file');
  await expect(page.getByTestId('track-title')).toHaveCount(0);
  await page.getByLabel('Import audio file').setInputFiles({
    name: 'broken.wav',
    mimeType: 'audio/wav',
    buffer: Buffer.from('RIFF broken WAV payload'),
  });
  await expect(page.getByRole('alert')).toContainText('could not be decoded');
  await expect(page.getByRole('alert')).toContainText('WAV');
  await expect(page.getByTestId('track-title')).toHaveCount(0);
  await importWav(page, wavFile('recovered.wav'));
  await expect(page.getByRole('alert')).toHaveCount(0);
});

test('replacing an active import terminates old analysis and saves only the latest audio', async ({
  page,
}) => {
  await page.goto('/');
  const started = page.waitForEvent('worker', (worker) => worker.url().includes('import-worker'));
  await page.getByLabel('Import audio file').setInputFiles(wavFile('superseded.wav', 120));
  const oldWorker = await started;
  const stopped = new Promise<void>((resolve) => oldWorker.once('close', () => resolve()));
  await importWav(page, wavFile('replacement.wav', 6, 2));
  await stopped;
  const record = await exportedRecord(page);
  expect(record.track.name).toBe('replacement.wav');
  expect(record.analysis.duration).toBeCloseTo(6, 2);
  await page.getByRole('button', { name: /Library/ }).click();
  await expect(
    page.getByRole('button', { name: 'Open analysis: replacement.wav', exact: true }),
  ).toHaveCount(1);
  await expect(
    page.getByRole('button', { name: 'Open analysis: superseded.wav', exact: true }),
  ).toHaveCount(0);
});

test('cancelling an active worker returns to import and leaves no saved result', async ({
  page,
}) => {
  await page.goto('/');
  const started = page.waitForEvent('worker', (worker) => worker.url().includes('import-worker'));
  await page.getByLabel('Import audio file').setInputFiles(wavFile('cancelled.wav', 120));
  const worker = await started;
  const stopped = new Promise<void>((resolve) => worker.once('close', () => resolve()));
  await page.getByRole('button', { name: 'Cancel analysis', exact: true }).click();
  await stopped;
  await expect(page.getByRole('button', { name: 'Open a song', exact: true })).toBeVisible();
  await expect(page.getByRole('alert')).toHaveCount(0);
  await page.getByRole('button', { name: /Library/ }).click();
  await expect(page.getByRole('button', { name: /^Open analysis:/ })).toHaveCount(0);
  await importWav(page, wavFile('after-cancel.wav', 4));
});

test('an active chord loop uses the edited boundary on the real playback clock', async ({
  page,
}) => {
  await page.goto('/');
  await importWav(page);
  const before = await exportedRecord(page);
  const first = before.analysis.segments[0];
  expect(first.start).toBe(0);
  expect(first.end).toBeGreaterThan(0.8);
  const end = Number((first.end / 2).toFixed(3));
  await page.getByRole('button', { name: 'Loop current chord', exact: true }).click();
  await page.getByRole('button', { name: 'Edit current chord', exact: true }).click();
  await page.getByLabel('End time in seconds').fill(String(end));
  await page.getByRole('button', { name: 'Save correction', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  expect((await exportedRecord(page)).analysis.segments[0].end).toBe(end);
  await page.getByLabel('Playback position').fill(String(Number((end - 0.1).toFixed(2))));
  await page.getByRole('button', { name: 'Play', exact: true }).click();
  let maximum = 0;
  await expect
    .poll(
      async () => {
        const position = Number(await page.getByLabel('Playback position').inputValue());
        maximum = Math.max(maximum, position);
        return position;
      },
      { intervals: [25], timeout: 4000 },
    )
    .toBeLessThan(0.3);
  expect(
    maximum,
    'loop must wrap near the new boundary, before reaching the old boundary',
  ).toBeLessThan(end + 0.45);
  await page.getByRole('button', { name: 'Pause', exact: true }).click();
  await expect(
    page.getByRole('button', { name: 'Loop current chord', exact: true }),
  ).toHaveAttribute('aria-pressed', 'true');
});

for (const width of [800, 1440, 2560]) {
  test(`empty and imported layouts fit a ${width}px window`, async ({ page }) => {
    await page.setViewportSize({ width, height: 960 });
    await page.goto('/');
    await expect(page.getByRole('button', { name: 'Open a song', exact: true })).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(
      true,
    );
    await page.screenshot({
      path: `docs/review-evidence/empty-${width}.png`,
      fullPage: true,
      animations: 'disabled',
    });
    await importWav(page);
    await expect(page.getByTestId('current-chord')).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(
      true,
    );
    await page.screenshot({
      path: `docs/review-evidence/imported-${width}.png`,
      fullPage: true,
      animations: 'disabled',
    });
  });
}
